Name:           ros-melodic-mrpt-slam
Version:        0.1.10
Release:        1%{?dist}
Summary:        ROS mrpt_slam package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/mrpt_slam
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-mrpt-ekf-slam-2d
Requires:       ros-melodic-mrpt-ekf-slam-3d
Requires:       ros-melodic-mrpt-graphslam-2d
Requires:       ros-melodic-mrpt-icp-slam-2d
Requires:       ros-melodic-mrpt-rbpf-slam
BuildRequires:  ros-melodic-catkin

%description
mrpt_slam

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sat Oct 05 2019 Vladislav Tananaev <v.d.tananaev@gmail.com> - 0.1.10-1
- Autogenerated by Bloom

* Sun Apr 14 2019 Vladislav Tananaev <v.d.tananaev@gmail.com> - 0.1.9-0
- Autogenerated by Bloom

* Fri Sep 21 2018 Vladislav Tananaev <v.d.tananaev@gmail.com> - 0.1.8-0
- Autogenerated by Bloom

* Wed Jul 25 2018 Vladislav Tananaev <v.d.tananaev@gmail.com> - 0.1.6-0
- Autogenerated by Bloom

