Name:           ros-melodic-mrpt-graphslam-2d
Version:        0.1.10
Release:        1%{?dist}
Summary:        ROS mrpt_graphslam_2d package

Group:          Development/Libraries
License:        BSD
URL:            http://www.mrpt.org/
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-mrpt-bridge
Requires:       ros-melodic-mrpt-msgs
Requires:       ros-melodic-mrpt1
Requires:       ros-melodic-multimaster-msgs-fkie
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rospy
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf
Requires:       ros-melodic-tf2
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-mrpt-bridge
BuildRequires:  ros-melodic-mrpt-msgs
BuildRequires:  ros-melodic-mrpt1
BuildRequires:  ros-melodic-multimaster-msgs-fkie
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rospy
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-tf2

%description
Implement graphSLAM using the mrpt-graphslam library, in an online fashion by
directly reading measurements off ROS Topics.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sat Oct 05 2019 Nikos Koukis <nickkouk@gmail.com> - 0.1.10-1
- Autogenerated by Bloom

* Sun Apr 14 2019 Nikos Koukis <nickkouk@gmail.com> - 0.1.9-0
- Autogenerated by Bloom

* Fri Sep 21 2018 Nikos Koukis <nickkouk@gmail.com> - 0.1.8-0
- Autogenerated by Bloom

* Wed Jul 25 2018 Nikos Koukis <nickkouk@gmail.com> - 0.1.6-0
- Autogenerated by Bloom

